apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::492443801558:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OLQHAGWYM89A
      username: system:node:{{EC2PrivateDNSName}}
      
    - groups:
      - system:masters
      rolearn: arn:aws:iam::492443801558:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-27T10:16:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "274214"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 76db3954-315c-4136-a873-f26e02dfbb68
